# Generated by Django 5.2.10 on 2026-02-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replies', models.ManyToManyField(blank=True, to='KCLTicketingSystems.reply')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('k_number', models.CharField(max_length=255, unique=True)),
                ('k_email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=255)),
                ('type_of_issue', models.CharField(max_length=255)),
                ('additional_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replies', models.ManyToManyField(blank=True, to='KCLTicketingSystems.reply')),
            ],
        ),
    ]
