# Generated by Django 5.2.10 on 2026-02-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KCLTicketingSystems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_k_number_when_not_empty',
        ),
        migrations.AlterModelTable(
            name='user',
            table='KCLTicketingSystems_user',
        ),
    ]
