# Generated by Django 5.2.10 on 2026-03-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Apply schema changes for 0002 notification meeting request so the data model stays aligned with ticketing features."""
    dependencies = [
        ('KCLTicketingSystems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meeting_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KCLTicketingSystems.meetingrequest'),
        ),
    ]
