# Generated by Django 5.2.8 on 2026-01-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KCLTicketingSystems', '0001_initial'),
    ]

    
    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='student_id',
        ),
    ]

    
