# Generated by Django 5.2.10 on 2026-02-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KCLTicketingSystems', '0002_ticket_admin_notes_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='KCLTicketingSystems_user',
        ),
    ]
