# Generated by Django 5.2.10 on 2026-02-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCLTicketingSystems', '0002_rename_issues_additional_details_and_add_type_of_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_images/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of_issue',
            field=models.CharField(max_length=255),
        ),
    ]
