# Generated by Django 5.2.10 on 2026-02-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCLTicketingSystems', '0002_rename_issues_additional_details_and_add_type_of_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Open', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of_issue',
            field=models.CharField(max_length=255),
        ),
    ]
