# Generated by Django 5.2.8 on 2026-02-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KCLTicketingSystems', '0002_rename_issues_additional_details_and_add_type_of_issue'),
        ('KCLTicketingSystems', '0002_rename_phone_profile_student_id'),
    ]

    operations = [
    ]
