# Generated by Django 5.2.10 on 2026-01-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCLTicketingSystems', '0002_rename_issues_additional_details_and_add_type_of_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of_issue',
            field=models.CharField(max_length=255),
        ),
    ]
