# Generated by Django 5.2.10 on 2026-02-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KCLTicketingSystems', '0003_alter_user_options_alter_user_k_number_and_more'),
        ('KCLTicketingSystems', '0003_alter_user_options_alter_user_table'),
    ]

    operations = [
    ]
