# Generated by Django 5.2.10 on 2026-02-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCLTicketingSystems', '0003_remove_ticket_k_number_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type_of_issue',
            field=models.CharField(max_length=255),
        ),
    ]
