# Generated by Django 5.2.10 on 2026-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    """Apply schema changes for 0004 alter ticket status so the data model stays aligned with ticketing features."""
    dependencies = [
        ('KCLTicketingSystems', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('new', 'New'), ('seen', 'Seen'), ('awaiting_response', 'Awaiting Student Response'), ('reported', 'Reported')], default='pending', max_length=20),
        ),
    ]
