# Generated by Django 5.2.10 on 2026-02-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KCLTicketingSystems', '0004_alter_ticket_type_of_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
